
### base, retuts all curencies
https://alt-exchange-rate.herokuapp.com/latest?base=USD

### start/end date
https://alt-exchange-rate.herokuapp.com/history?start_at=2020-03-10&end_at=2020-04-10&base=BGN&symbols=EUR


### limits response
https://alt-exchange-rate.herokuapp.com/latest?base=USD&symbols=GBP  