users = User.create([
                      { username: 'Tommy', email: 'tommy@test.com', password: 'password' },
                      { username: 'Bobby', email: 'bobby@test.com', password: 'password' },
                      { username: 'Sarah', email: 'sarah@test.com', password: 'password' },
                      { username: 'Lilly', email: 'lilly@test.com', password: 'password' },
                      { username: 'Jimmy', email: 'jimmy@test.com', password: 'password' },
                      { username: 'Cammy', email: 'cammy@test.com', password: 'password' }
                    ])

attempts = Attempt.create([
                            { user_id: 1, image_url: 'url-here', success: true },
                            { user_id: 1, image_url: 'url-here', success: true },
                            { user_id: 1, image_url: 'url-here', success: true },
                            { user_id: 1, image_url: 'url-here', success: true },
                            { user_id: 2, image_url: 'url-here', success: false },
                            { user_id: 2, image_url: 'url-here', success: true },
                            { user_id: 2, image_url: 'url-here', success: true },
                            { user_id: 2, image_url: 'url-here', success: false },
                            { user_id: 2, image_url: 'url-here', success: false },
                            { user_id: 2, image_url: 'url-here', success: false },
                            { user_id: 2, image_url: 'url-here', success: false },
                            { user_id: 2, image_url: 'url-here', success: false },
                            { user_id: 3, image_url: 'url-here', success: false },
                            { user_id: 3, image_url: 'url-here', success: false },
                            { user_id: 3, image_url: 'url-here', success: true },
                            { user_id: 3, image_url: 'url-here', success: true },
                            { user_id: 3, image_url: 'url-here', success: true },
                            { user_id: 3, image_url: 'url-here', success: true },
                            { user_id: 3, image_url: 'url-here', success: true },
                            { user_id: 3, image_url: 'url-here', success: true },
                            { user_id: 3, image_url: 'url-here', success: true },
                            { user_id: 3, image_url: 'url-here', success: false },
                            { user_id: 4, image_url: 'url-here', success: false },
                            { user_id: 4, image_url: 'url-here', success: false },
                            { user_id: 4, image_url: 'url-here', success: true },
                            { user_id: 4, image_url: 'url-here', success: true },
                            { user_id: 4, image_url: 'url-here', success: false },
                            { user_id: 5, image_url: 'url-here', success: true },
                            { user_id: 5, image_url: 'url-here', success: true },
                            { user_id: 5, image_url: 'url-here', success: true },
                            { user_id: 5, image_url: 'url-here', success: true },
                            { user_id: 5, image_url: 'url-here', success: false },
                            { user_id: 6, image_url: 'url-here', success: false },
                            { user_id: 6, image_url: 'url-here', success: false },
                            { user_id: 6, image_url: 'url-here', success: false },
                            { user_id: 6, image_url: 'url-here', success: false },
                            { user_id: 6, image_url: 'url-here', success: true },
                            { user_id: 6, image_url: 'url-here', success: true },
                            { user_id: 6, image_url: 'url-here', success: true },
                            { user_id: 6, image_url: 'url-here', success: true },
                            { user_id: 6, image_url: 'url-here', success: true },
                            { user_id: 7, image_url: 'url-here', success: true },
                            { user_id: 7, image_url: 'url-here', success: false },
                            { user_id: 7, image_url: 'url-here', success: false },
                            { user_id: 7, image_url: 'url-here', success: true },
                            { user_id: 8, image_url: 'url-here', success: true },
                            { user_id: 8, image_url: 'url-here', success: true },
                            { user_id: 8, image_url: 'url-here', success: true },
                            { user_id: 8, image_url: 'url-here', success: true },
                            { user_id: 8, image_url: 'url-here', success: true },
                            { user_id: 8, image_url: 'url-here', success: false},
                            { user_id: 8, image_url: 'url-here', success: false }
                          ])

Attempt.where(success: false).update(image_url: "https://res.cloudinary.com/dzdwgxbjl/image/upload/v1607100450/sample.jpg")
Attempt.where(success: true).update(image_url: "https://res.cloudinary.com/dzdwgxbjl/image/upload/s--u4cUekWT--/v1614866396/zfdtocsuf8ucceive6zx.jpg")